version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-container
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=
      - PORT=5000
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend-container
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network: